// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void registnewuser()
    {
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
        driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
        driver.FindElement(By.Id("signupName")).Click();
        driver.FindElement(By.Id("signupName")).SendKeys("rrrr");
        driver.FindElement(By.Id("signupLastName")).Click();
        driver.FindElement(By.Id("signupLastName")).SendKeys("tttt");
        driver.FindElement(By.Id("signupEmail")).Click();
        driver.FindElement(By.Id("signupEmail")).SendKeys("asdsdasdzxzxcvdfasd@gmk.com");
        driver.FindElement(By.Id("signupPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("Qwerty12");
        driver.FindElement(By.XPath("//button[@class=\'btn btn-primary\']")).Click();
        {
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(10));
            wait.Until(driver => driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']")).Count > 0);
        }
        var elements = driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']"));
        Assert.True(elements.Count > 0);
    }
}
